ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.opsora.space
CATALOGUE_HOST: catalogue-dev.opsora.space
REDIS_HOST: redis-dev.opsora.space
USER_HOST: user-dev.opsora.space
CART_HOST: cart-dev.opsora.space
MYSQL_HOST: mysql-dev.opsora.space
SHIPPING_HOST: shipping-dev.opsora.space
RABBITMQ_HOST: rabbitmq-dev.opsora.space
PAYMENT_HOST: payment-dev.opsora.space
DISPATCH_HOST: dispatch-dev.opsora.space
