- name: "Copying {{ component }} file"
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: "Installing {{ component }}"
  ansible.builtin.dnf:
    name: mongodb-org
    state: present

- name: allow remote connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: "Enabling {{ component }} service"
  ansible.builtin.service:
    name: mongodb-org
    enabled: yes
    state: present