- name: Creating user
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Calling dependencies
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: "Starting {{ component }} service"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: " Copying {{ component }} service"
  ansible.builtin.template:
    src: user.service.j2
    dest: /etc/systemd/system/user.service

- name: Deamond Reload
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true

- name: start user
  ansible.builtin.service:
    name: "{{ comment }}"
    state: restarted
    enabled: yes


