- name: Creating user
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Calling dependencies
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup.yaml

- name: "Starting {{ component }} service"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml
    
- name: start user
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes


