- name: Instaling MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Starting and Enabling Mysqld
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: restarted

- name: setting default password for Mysqld
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1